# 1. Create a Pandas Series that contains the following data: 4, 8, 15, 16, 23, and 42. Then, print the series.
ANSWER:

    import pandas as pd

    data = [4, 8, 15, 16, 23, 42]
    series = pd.Series(data)
    print(series)

OUTPUT:

    0     4
    1     8
    2    15
    3    16
    4    23
    5    42
    dtype: int64

# 2. Create a variable of list type containing 10 elements in it, and apply pandas.Series function on the variable print it.
ANSWER:

    import pandas as pd

    my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    my_series = pd.Series(my_list)
    print(my_series)

OUTPUT:

    0     1
    1     2
    2     3
    3     4
    4     5
    5     6
    6     7
    7     8
    8     9
    9    10
    dtype: int64

# 3. Create a Pandas DataFrame that contains the following data:
    
    Name, Age, Gender
    Alice, 25, Female
    Bob, 30, Male
    Claire, 27, Female

    Then, print the DataFrame.
    
ANSWER:

    import pandas as pd

    data = {
        'Name': ['Alice', 'Bob', 'Claire'],
        'Age': [25, 30, 27],
        'Gender': ['Female', 'Male', 'Female']
    }

    df = pd.DataFrame(data)
    print(df)

OUTPUT:

         Name  Age  Gender
    0   Alice   25  Female
    1     Bob   30    Male
    2  Claire   27  Female

# 4. What is ‘DataFrame’ in pandas and how is it different from pandas.series? Explain with an example.
ANSWER:

In pandas, a DataFrame is a 2-dimensional labeled data structure that can store data of different types, such as numeric, string, and Boolean. It is similar to a table in a relational database or a spreadsheet in a Microsoft Excel file, where each row represents a separate observation or record, and each column represents a separate variable or feature. A DataFrame can be thought of as a collection of Pandas Series, where each Series represents a column of the DataFrame.

On the other hand, a Pandas Series is a one-dimensional labeled array that can hold data of any type, such as integer, float, string, and Boolean. It can be thought of as a single column of a DataFrame or a single variable in a dataset.

Here's an example that shows the difference between a DataFrame and a Series:

    import pandas as pd

    # Create a DataFrame
    data = {
        'Name': ['Alice', 'Bob', 'Claire'],
        'Age': [25, 30, 27],
        'Gender': ['Female', 'Male', 'Female']
    }
    df = pd.DataFrame(data)

    # Create a Series from the 'Age' column of the DataFrame
    age_series = df['Age']

    # Display the DataFrame and the Series
    print("DataFrame:")
    print(df)
    print("\nSeries:")
    print(age_series)

OUTPUT:

    DataFrame:
         Name  Age  Gender
    0   Alice   25  Female
    1     Bob   30    Male
    2  Claire   27  Female

    Series:
    0    25
    1    30
    2    27
    Name: Age, dtype: int64

# 5. What are some common functions you can use to manipulate data in a Pandas DataFrame? Can you give an example of when you might use one of these functions?
ANSWER:

There are numerous functions and methods available in Pandas that can be used to manipulate data in a DataFrame. Some common functions and methods are:

    head(n): Returns the first n rows of the DataFrame.
    tail(n): Returns the last n rows of the DataFrame.
    info(): Displays information about the DataFrame, such as the number of rows and columns, column data types, and memory usage.
    describe(): Computes basic summary statistics for each column, such as count, mean, standard deviation, minimum, and maximum values.
    drop(columns=cols): Removes one or more columns from the DataFrame.
    dropna(): Removes rows with missing values.
    fillna(value): Fills in missing values with a specified value.
    groupby(col): Groups the DataFrame by a specified column and returns a GroupBy object, which can be used to perform aggregate operations such as mean, sum, and count on each group.
    sort_values(by=col): Sorts the DataFrame by a specified column in ascending order.
    pivot_table(values, index, columns): Creates a pivot table that summarizes the data in the DataFrame by aggregating values based on one or more columns.

Here's an example of when you might use the groupby() function:

Suppose you have a DataFrame containing data on the sales of different products in different regions, and you want to calculate the total sales for each product across all regions. You can use the groupby() function to group the data by the Product column and then apply the sum() function to the Sales column to get the total sales for each product:

    import pandas as pd

    # Create a DataFrame
    data = {
        'Region': ['North', 'North', 'South', 'South', 'East', 'West'],
        'Product': ['A', 'B', 'A', 'B', 'A', 'B'],
        'Sales': [100, 200, 150, 250, 180, 220]
    }
    df = pd.DataFrame(data)

    # Group the data by product and calculate the total sales for each product
    sales_by_product = df.groupby('Product')['Sales'].sum()

    # Display the result
    print(sales_by_product)

OUTPUT:

    Product
    A    430
    B    670
    Name: Sales, dtype: int64

# 6. Which of the following is mutable in nature Series, DataFrame, Panel?
ANSWER:

The Pandas Series and DataFrame are mutable in nature, while the Panel is immutable.

In other words, it is possible to modify the contents of a Series or a DataFrame after it has been created by adding, removing, or updating values. However, it is not possible to modify the contents of a Panel after it has been created. Instead, a new Panel must be created if any changes need to be made.

Note that although Series and DataFrame are mutable, certain operations such as sorting and grouping can create new objects rather than modifying the existing ones. In such cases, the original object remains unchanged, and a new object is returned with the desired modifications.

# 7. Create a DataFrame using multiple Series. Explain with an example.
ANSWER:

    import pandas as pd

    # create a Pandas Series for each column
    names = pd.Series(['Alice', 'Bob', 'Claire'])
    ages = pd.Series([25, 30, 27])
    genders = pd.Series(['Female', 'Male', 'Female'])

    # create a DataFrame using the Series
    df = pd.DataFrame({'Name': names, 'Age': ages, 'Gender': genders})

    # print the DataFrame
    print(df)

OUTPUT:

         Name  Age  Gender
    0   Alice   25  Female
    1     Bob   30    Male
    2  Claire   27  Female